# Generated by Django 5.1 on 2024-09-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('employer', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.candidate'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ManyToManyField(to='employer.job'),
        ),
    ]
