# Generated by Django 5.1 on 2024-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_index=True, max_length=255)),
                ('job_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('job_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Work fom office', 'Work fom office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=255, null=True)),
                ('job_description', models.TextField()),
                ('no_of_openings', models.PositiveBigIntegerField(blank=True, null=True)),
                ('required_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('candidates_applied', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tbl_job',
                'managed': True,
            },
        ),
    ]
