# Generated by Django 5.1 on 2024-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='hiring_for',
            field=models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], default='Company', max_length=30),
        ),
    ]
